name: Publish stories if changed

on:
  push:
    branches:
      - main
    paths: ["src/components/**"]
  pull_request:
    branches:
      - main
    paths: ["src/components/**"]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm install
          npm run build-storybook
      - name: Deploy storybook to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          ssh-key: ${{ secrets.GP_TOKEN }}